# Generated by Django 4.1.3 on 2022-11-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="preparation_step",
            new_name="preparation_steps",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="preparation_step_is_html",
            new_name="preparation_steps_is_html",
        ),
    ]
